External idp impl
abbra/freeipa pull request #78
Opened 2021-06-25 16:44 UTC by flo-renaud

- External IdP schema: use octetstring syntax for client secret
- External Identity Provider plugin implementation
- External Idp: add XMLRPC tests

2021-06-29 09:16 UTC, abbra requested changes
Thank you for the PR. It looks fine in general, couple comments inline. There are many places where you have used `u"..."` for unicode strings but this is not really needed with Python 3 anymore, could you please remove all the prefixes?
Also should we add 'admins' group to the default privilege?

2021-06-29 09:16 UTC, abbra commented on ipaserver/plugins/idp.py
> +        u'google': (
you don't need to use `u'...'` with Python 3 anymore, just use normal strings here and in other places, please.

2021-06-29 09:16 UTC, abbra commented on ipaserver/plugins/idp.py
> +            'default_privileges': {'External Idp server Administrators'}
Please change `Idp` to `IdP` here.

2021-06-29 09:16 UTC, abbra commented on ipaserver/plugins/idp.py
> +            'default_privileges': {'External Idp server Administrators'}
Please change `Idp` to `IdP` here.

2021-06-29 09:16 UTC, abbra commented on ipaserver/plugins/idp.py
> +            'default_privileges': {'External Idp server Administrators'}
Please change `Idp` to `IdP` here.

2021-06-29 09:16 UTC, abbra commented on ipaserver/plugins/idp.py
> +            'default_privileges': {'External Idp server Administrators'}
Please change `Idp` to `IdP` here.

2021-06-29 09:16 UTC, abbra commented on ipatests/test_xmlrpc/test_idp_plugin.py
> +            error=u"must be one of 'google', 'github', 'microsoft-common', "
Same here -- no need to use `u"..."` for strings anymore

2021-06-29 13:56 UTC, flo-renaud commented
Hi @abbra 
thanks for the review. I removed the unicode prefix (hope I didn't forget it anywhere) and fixed the uppercase in IdP.

> Also should we add 'admins' group to the default privilege?

By default admins can manage any entry thanks to the following ACI on the basedn:
```
aci: (targetattr != "userPassword || krbPrincipalKey || sambaLMPassword || sam
 baNTPassword || passwordHistory || krbMKey || krbPrincipalName || krbCanonica
 lName || krbPwdHistory || krbLastPwdChange || krbExtraData || krbLastSuccessf
 ulAuth || krbLastFailedAuth || ipaUniqueId || memberOf || enrolledBy || ipaNT
 Hash || ipaProtectedOperation")(version 3.0; acl "Admin can manage any entry"
 ; allow (all) groupdn = "ldap:///cn=admins,cn=groups,cn=accounts,dc=ipa,dc=te
 st";)

```

2021-06-29 15:13 UTC, abbra commented
Thanks. I think there is one place with `u'..'` left in tests. API.txt file has `u'..'` as well but those are generated and kept this way so they are OK.

2021-06-29 15:31 UTC, flo-renaud commented
I forgot to re-run makeaci and makeapi, it may fix some of the u'' issues. I'm on it...

2021-06-30 14:30 UTC, abbra commented
Right, it was not in the new code -- only in the context lines.

2021-06-30 14:30 UTC, merged

2021-06-30 14:31 UTC, abbra commented
Merged, thanks!